version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: checkout-backend
    working_dir: /app/backend
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - db
    networks:
      - checkout-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: checkout-frontend
    working_dir: /app/frontend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - checkout-network

  db:
    image: postgres:14
    container_name: checkout-db
    restart: always
    environment:
      POSTGRES_USER: checkout_user
      POSTGRES_PASSWORD: checkout_password
      POSTGRES_DB: checkout_db
    ports:
      - "5432:5432"
    networks:
      - checkout-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  checkout-network:
    driver: bridge

volumes:
  db_data:
    driver: local
